server:
  port: 15450
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:h2:tcp://localhost/~/springexample
    username: sa
    password:
    driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          #        show_sql: true # systemOut log
          format_sql: true
example:
  value:
    order: 1000
  server:
    url: 127.0.0.1
    port: 15450